services:
#    eshop_ledaagro.example:
#        class: Eshop\SampleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Eshop\SampleBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']