imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@EshopSampleBundle/Resources/config/services.yml" }
    - { resource: ckfinder_config.php }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ua

ckfinder:
    connector:
        licenseName: LICENSE-NAME
        licenseKey: LICENSE-KEY
        authenticationClass: Eshop\SampleBundle\CustomCKFinderAuth\CustomCKFinderAuth
        resourceTypes:
            MyResource:
                name: MyResource
                backend: default
                directory: myResource

framework:
    #esi: ~
#    default_locale: en
    translator: { fallbacks: ['ru'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']


fos_ck_editor:
    configs:
        my_config:
            toolbar: [ ["Source", "-", "Save"], ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Image' , 'Superscript', '-', 'RemoveFormat'] , , "/", ["Anchor"], "/", ["Maximize"] ]
            uiColor:                "#000000"
#            base_path: "ckeditor"
#            js_path: "ckeditor/ckeditor.js"
#            filebrowserUploadRoute: "my_route"
#            extraPlugins:           "wordcount"


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
#        less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/lib/node_modules]

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                replace: Eshop\SampleBundle\DQL\ReplaceFunction

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username: ivanltestl7@gmail.com
    password: naclime86#
#    host: localhost
    spool: { type: memory }


sensio_framework_extra:
   router:
        annotations: false

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
